name: docker

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  info:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install docker via brew
        if: matrix.os == 'macos-latest'
        run: |
          which brew || true
          apt update && apt install -y curl
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install --cask docker 
      - name: Test docker
        run: |
          docker version
          docker info