name: docker

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  info:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Updating and upgrading brew
        if: matrix.os == 'macos-latest'
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew --version
      - name: Install and start docker
        if: matrix.os == 'macos-latest'
        run: |
          bash install-docker.sh
          bash start-docker.sh
      - name: Test docker
        run: |
          docker version
          docker info